version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_app_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=weather_app_dev
      - DB_PORT=5432
      - SESSION_SECRET=your-secret-key-here
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/.env:/app/backend/.env:ro
    restart: unless-stopped

volumes:
  postgres_data: